#!/bin/sh

# Llamamos a imo para notificar a nifi.
/app/imo/imo nifi notification \
    --nifi-host imk-nifi \
    --nifi-port 8888 \
    --nsq-producer-tcp-address imk-nsqd:4150 \
    --sftpgo-operation "$1" \
    --sftpgo-username "$2" \
    --sftpgo-path "$3" \
    --sftpgo-target "$4" > /app/imo/notification-imo.log 2>&1

